# Generated by Django 5.0 on 2024-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('mileage', models.FloatField()),
                ('v_type', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('v_seat_type', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('o_contact', models.BigIntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
